#系统内置设置
talk-system:
  #token密钥设置
  token-secret: serliunxvarytalktoken
  #token过期时间(小时)
  token-expire-hour: 1
  #token头标识
  auth-header: Authorization
  #redis键
  redis-prefix:
    #主键
    main-prefix: "vary_talk:"
    #在线用户
    online-users: "user_online:"

#服务器设置
server:
  port: 6666
  servlet:
    context-path: /api
spring:
  #数据源设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vary_talk?autoReconnect=true&characterEncoding=utf8
    username: root
    password: 2636257370
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        log4j:
          enabled: true
          statement-log-enabled: true
  banner:
    #banner设置
    location: classpath:other/banner.txt
    charset: UTF-8
  servlet:
    multipart:
      #允许上传的最大文件尺寸(单次)
      max-file-size: 1GB
  mvc:
    #数据校验日志开关
    log-resolved-exception: false
  data:
    #redis设置
    redis:
      #连接地址
      host: localhost
      #端口号
      port: 6379
      #数据库序号
      database: 0
      connect-timeout: 10000
      password: 2636257370
      lettuce:
        pool:
          max-wait: -1
          max-idle: 8
          min-idle: 0
          #连接池最大连接数
          max-active: 25
#mybatis设置
mybatis:
  #mapper扫描地址
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: github.serliunx.**.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

#日志设置
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss(SSS)
  level:
    github.serliunx.*: debug

#分页插件设置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql